---
#------------------------------- DANDO PERMISOS DE EJECUCION
- name: Check if package tablib exists
  command: pwd

#------------------------------- INICIALIZANDO ARCHIVO DE RESULTADOS
- name: Check if package tablib exists
  register: pkg_check
  command: ./plays/bin/checkPackage.py

- name: Installing tablib module
  pip: 
    name: tablib
  when: pkg_check.stdout.find('ModuleNotFoundError') != -1 or pkg_check.stdout.find('No module named') != -1

#------------------------------- CONVIRTIENDO
- name: Check if package tablib exists
  command: ./plays/bin/json2xlsx.py {{ inputfile }} {{ outputfile }}
