---
#------------------------------- PREREQUISITOS
- name: Inicialice file
  hosts: localhost
  vars:
    start: "["

  tasks:
    - name: Create Json File                                                                               
      copy:
        content: "{{ start }}"
        dest: "/tmp/jstack.json"
      delegate_to: 127.0.0.1
# - name: Checking if json2xlsx libraries are installed
#   hosts: localhost

#   tasks: 
#     - name: Check if package tablib exists
#       register: pkg_check
#       command: ./plays/bin/checkPackage.py

#     - name: Installing tablib module
#       pip: 
#         name: tablib
#       when: pkg_check.stdout.find('ModuleNotFoundError') != -1 or pkg_check.stdout.find('No module named') != -1

# #------------------------------- CONVIRTIENDO
# - name: Checking if json2xlsx libraries are installed
#   hosts: localhost

#   tasks: 
#     - name: Check if package tablib exists
#       command: ./plays/bin/json2xlsx.py {{ inputfile }} {{ outputfile }}