---
#------------------------------- DANDO PERMISOS DE EJECUCION
- name: Seting execution perms checkPackage.py
  command: chmod +x plays/bin/checkPackage.py

- name: Seting execution perms json2xlsx.py
  command: chmod +x plays/bin/json2xlsx.py  

#------------------------------- INICIALIZANDO ARCHIVO DE RESULTADOS
- name: Check if package tablib exists
  register: pkg_check
  command: python plays/bin/checkPackage.py
  ignore_errors: True
  
- name: Installing tablib module
  pip: 
    name: tablib
  when: pkg_check.stderr.find('ModuleNotFoundError') != -1 or pkg_check.stderr.find('No module named') != -1

#------------------------------- INICIALIZANDO ARCHIVO DE RESULTADOS
- name: Check if package tablib exists
  register: pkg_check
  command: python -c "import tablib"
  ignore_errors: True

#------------------------------- CONVIRTIENDO
- name: Check if package tablib exists
  command: python plays/bin/json2xlsx.py {{ inputfile }} {{ outputfile }}

