---
- name: Add Route To Ansible Host
  #hosts: 127.0.0.1
  hosts: 10.49.5.209
  connection: local
  vars:
    interface: placeholder
    mask: placeholder
    destination: placeholder
    route_action: placeholder
  gather_facts: false
  tasks:
    - name: Add Static Route 
      when: route_action == "add"
      register: output
      shell: /sbin/route add -net "{{ destination }}" netmask "{{ mask }}" gw "{{ interface }}"

    - name: Delete Static Route 
      when: route_action == "delete"
      register: output
      shell: /sbin/route del -net "{{ destination }}" netmask "{{ mask }}" gw "{{ interface }}"

    - name: List Static Routes 
      #when: route_action == "list"
      register: output
      shell: cd ~ && echo |1|BK9rfiP7f2uSfCx5ggsChbX2LJg=|XXRFI81ATUzz8ceSuENN4G8yyT8= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMnV10rXVHT1+S8A+9JBL+EyIAyqKdu4W5OmCisNzd8Zc/bygUkhh3Rnrb3vN2vxUbKDmGYP2BG6SOKPIo0vVJU= >> .ssh/known_hosts || ssh ubuntu@10.49.5.209 "route -n"
      #shell: ssh ubuntu@10.49.5.209 "route -n"
      #shell: pwd && cd linuxFiles && chmod 777 addRoute.sh && ls -la && ./addRoute.sh
        #cmd: /sbin/route -n
        #cmd: ping -c 4 10.49.5.209
        #chdir: /etc/ansible

    - name: Print Output
      debug: var=output.stdout_lines
