---
- name: Add Route To Ansible Host
  hosts: localhost
  vars:
    interface: placeholder
    mask: placeholder
    destination: placeholder
    action: placeholder
  gather_facts: false
  tasks:
    - name: Add Static Route 
      when: action == "add"
      register: output
      command: route add -net "{{ destination }}" netmask "{{ mask }}" gw "{{ interface }}"

    - name: Add Static Route 
      when: action == "delete"
      register: output
      command: route del -net "{{ destination }}" netmask "{{ mask }}" gw "{{ interface }}"

    - name: Add Static Route 
      when: action == "list"
      register: output
      command: route -n

    - name: Print Output
      debug: var=output.sdout_lines
