---
- name: Add Route To Ansible Host
  #hosts: 127.0.0.1
  hosts: 10.49.5.209
  connection: local
  vars:
    interface: placeholder
    mask: placeholder
    destination: placeholder
    route_action: placeholder
  gather_facts: false
  tasks:
    - name: Add Static Route 
      when: route_action == "add"
      register: addoutput
      expect:
        command: ssh -o StrictHostKeyChecking=no ubuntu@10.49.5.209 'sudo route add -net "{{ destination }}" netmask "{{ mask }}" gw "{{ interface }}"'
        responses: 
          (?i)password: "atomic"
      #shell: /sbin/route add -net "{{ destination }}" netmask "{{ mask }}" gw "{{ interface }}"

    - name: Print Add Output
      when: route_action == "add"
      debug: var=addoutput.stdout_lines

    - name: Delete Static Route 
      when: route_action == "delete"
      register: deloutput
      expect:
        command: ssh -o StrictHostKeyChecking=no ubuntu@10.49.5.209 'sudo route del -net "{{ destination }}" netmask "{{ mask }}" gw "{{ interface }}"'
        responses: 
          (?i)password: "atomic"
      #shell: /sbin/route del -net "{{ destination }}" netmask "{{ mask }}" gw "{{ interface }}"

    - name: Print Del Output
      when: route_action == "delete"
      debug: var=deloutput.stdout_lines

    - name: List Static Routes 
      when: route_action == "list"
      register: listoutput
      expect:
        command: ssh -o StrictHostKeyChecking=no ubuntu@10.49.5.209 'route -n'
        responses: 
          (?i)password: "atomic"
      #shell: /sbin/route -n

    - name: Print Del Output
      when: route_action == "list"
      debug: var=listoutput.stdout_lines

#    - name: Install pexpect
#      register: output
#      pip:
#        name: pexpect
#      become: yes