---
- name: Add Route To Ansible Host
  hosts: 10.49.5.209
  connection: local
  vars:
    interface: placeholder
    mask: placeholder
    destination: placeholder
    route_action: placeholder
    sshpass: "atomic"
  gather_facts: false
  tasks:
#------------------------------- ADD ROUTE TASK
    - name: Add Static Route 
      when: route_action == "add"
      register: addoutput
      expect:
        command: ssh -o StrictHostKeyChecking=no ubuntu@10.49.5.209 'sudo route add -net "{{ destination }}" netmask "{{ mask }}" gw "{{ interface }}"'
        responses: 
          (?i)password: "{{ sshpass }}"
      ignore_errors: True
      no_log: True

    - name: Add Static Route Error
      when: route_action == "add" and addoutput.rc != 0
      fail:
        msg: 'ADD ROUTE FAILIED: "{{ addoutput.stdout_lines }}"'

    - name: Print Add Output
      when: route_action == "add" and addoutput.rc == 0
      debug: var=addoutput.stdout_lines

#------------------------------- DELETE ROUTE TASK
    - name: Delete Static Route 
      when: route_action == "delete"
      register: deloutput
      expect:
        command: ssh -o StrictHostKeyChecking=no ubuntu@10.49.5.209 'sudo route del -net "{{ destination }}" netmask "{{ mask }}" gw "{{ interface }}"'
        responses: 
          (?i)password: "{{ sshpass }}"
      ignore_errors: True
      no_log: True

    - name: Delete Static Route Error
      when: route_action == "delete" and deloutput.rc != 0
      fail:
        msg: 'DELETE ROUTE FAILIED: "{{ deloutput.stdout_lines }}"'

    - name: Print Del Output
      when: route_action == "delete" and deloutput.rc == 0
      debug: var=deloutput.stdout_lines

#------------------------------- LIST ROUTES TASK
    - name: List Static Routes 
      when: route_action == "list"
      register: listoutput
      expect:
        command: ssh -o StrictHostKeyChecking=no ubuntu@10.49.5.209 'route -n'
        responses: 
          (?i)password: "{{ sshpass }}"
      ignore_errors: True
      no_log: True

    - name: List Static Route Error
      when: route_action == "list" and listoutput.rc != 0
      fail:
        msg: 'LIST ROUTES FAILIED: "{{ listoutput.stdout_lines }}"'

    - name: Print List Output
      when: route_action == "list" and listoutput.rc == 0
      debug: var=listoutput.stdout_lines

#------------------------------- RESTART NETWORK SERVICE TASK
    - name: Restart Network Service
      when: route_action == "restart"
      register: restarttoutput
      expect:
        command: ssh -o StrictHostKeyChecking=no ubuntu@10.49.5.209 'sudo  /etc/init.d/networking restart'
        responses: 
          (?i)password: "{{ sshpass }}"
      ignore_errors: True
      no_log: True

    - name: Restart Network Service Error
      when: route_action == "restart" and restarttoutput.rc != 0
      fail:
        msg: 'RESTART NETWORK SERVICE FAILIED: "{{ restarttoutput.stdout_lines }}"'

    - name: Print Restart Network Service Output
      when: route_action == "restart" and restarttoutput.rc == 0
      debug: var=restarttoutput.stdout_lines
