---
- name: Add Route To Ansible Host
  hosts: localhost
  connection: local
  vars:
    interface: placeholder
    mask: placeholder
    destination: placeholder
    action: placeholder
  gather_facts: false
  tasks:
    - name: Add Static Route 
      when: action == "add"
      register: output
      command: /sbin/route add -net "{{ destination }}" netmask "{{ mask }}" gw "{{ interface }}"

    - name: Delete Static Route 
      when: action == "delete"
      register: output
      command: /sbin/route del -net "{{ destination }}" netmask "{{ mask }}" gw "{{ interface }}"

    - name: List Static Routes 
      when: action == "list"
      register: output
      command: /sbin/route -n

    - name: Print Output
      debug: var=output
