---
- name: Add Route To Ansible Host
  hosts: localhost
  vars:
    interface: placeholder
    gateway: placeholder
    destination: placeholder
  gather_facts: false
  tasks:
    # 'argv' is a parameter, indented one level from the module
    - name: Add Static Route for BackUp Net
      register: addrute
      when: "{{ interface }}" == "10.49.5.209"
      command:
        argv:
          - ip route add -net
          - "{{ destination }}" gw
          - "{{ gateway }}" dev ens3

    # 'argv' is a parameter, indented one level from the module
    - name: Add Static Route for Internet Net
      register: addrute
      when: "{{ interface }}" == "10.10.2.155"
      command:
        argv:
          - ip route add -net
          - "{{ destination }}" gw
          - "{{ gateway }}" dev ens4

    - name: Print Output
      debug: var=addrute.sdout_lines
