---
- name: Add Route To Ansible Host
  #hosts: 127.0.0.1
  hosts: localhost
  connection: local
  vars:
    interface: placeholder
    mask: placeholder
    destination: placeholder
    route_action: placeholder
  gather_facts: false
  tasks:
    - name: Add Static Route 
      when: route_action == "add"
      register: output
      shell: /sbin/route add -net "{{ destination }}" netmask "{{ mask }}" gw "{{ interface }}"

    - name: Delete Static Route 
      when: route_action == "delete"
      register: output
      shell: /sbin/route del -net "{{ destination }}" netmask "{{ mask }}" gw "{{ interface }}"

    - name: List Static Routes 
      when: route_action == "list"
      register: output
      shell: 
        cmd: ifconfig
        #chdir: /etc/ansible

      #command: /sbin/route -n

    - name: Print Output
      debug: var=output.stdout_lines
