---
- name: Deploy New Bot
  hosts: 192.168.50.6
  vars:
    # To be defined by the user
    bot_name: placeholder

  gather_facts: false
  tasks:
#------------------------------- GETTING NEW BOT'S PORT FROM HAPROXI CONFIG FILE
    - name: Get bot port from haproxy
      register: bot_port
      command: "sudo bash /kai/botfs/deploy/getNextPort.sh"

    - name: Bot Port 
      debug: var=bot_port

#------------------------------- CREATING DIRECTORY TREE AND FILES FOR THE NEW BOT

    - name: Creating bot's basic files and directory tree
      vars: 
        port: "{{ bot_port.stdout|int }}"
      when: 40100 < port
      register: output1
      command: "sudo /bin/bash /kai/botfs/deploy/deployNewBot.sh {{ bot_name }} {{ port }}"
      #args:
      #  chdir: somedir/
      #shell:
      #  cmd: pwd 
      #  #chdir: /home/kai

    #- name: Change the working directory to somedir/ before executing the command.
    #  when: bot_name == "test"
    #  register: output1
    #  command: "chmod +x DeployBot/CreateFiles.sh"
      #args:
      #  chdir: somedir/


    - name: Print Output
      #when: output.rc == 0 # route_action == "add" and 
      debug: var=output1 #.stdout_lines

    #- name: Change the working directory to somedir/ before executing the command.
    #  when: bot_name == "test"
    #  register: output2
    #  command: "DeployBot/CreateFiles.sh"
      #args:
      #  chdir: somedir/


    #- name: Print Output
    #  #when: output.rc == 0 # route_action == "add" and 
    #  debug: var=output2 #.stdout_lines

