---
- name: Deploy New Bot
  #hosts: 10.10.2.9
  hosts: localhost
  connection: local
  vars:
    bot_name: placeholder
  #  mask: placeholder
  #  destination: placeholder
  #  route_action: placeholder
    sshpass: "atomic"
  #  
    #ADD ROUTE COMMANDS
    test: echo "test"
  #  add_static_route_internet: echo up route add -net {{ destination }} netmask {{ mask }} gw {{ interface }} dev
  #  tee: sudo tee -a /etc/network/interfaces

    #DELETE ROUTE COMMANDS
  #  del_tmp_route: sudo route del -net {{ destination }} netmask {{ mask }} gw {{ interface }}
  #  del_static_route: sudo sed -i '/up route add -net {{ destination }} netmask {{ mask }} gw {{ interface }}/d' /etc/network/interfaces

  gather_facts: false
  tasks:
#------------------------------- ADD ROUTE INTERNET TASK
    - name: TestConnection
      when: bot_name == "no"
      block:
        - name: testserver
          register: output
          expect:
            command: ssh -o StrictHostKeyChecking=no kai@10.10.2.9 '{{ test }}'
            responses: 
              (?i)password: "{{ sshpass }}"
          ignore_errors: True
          no_log: True

    - name: List Static Routes 
      when: bot_name == "test"
      warn: false
      register: output
      shell: apt-get update -y && apt-get install -y python-pexpect

        #- name: Add Internet Route Error
        #  when: output.rc != 0 #route_action == "add" and interface == "10.10.2.254" and 
        #  fail:
        #    msg: 'ADD ROUTE FAILIED: "{{ output.stdout_lines }}"'
    - name: Print Output
      #when: output.rc == 0 # route_action == "add" and 
      debug: var=output #.stdout_lines