---
#------------------------------- PLAYBOOK SCRIPT NIRVANA
- name: Depura Logs Web Logic Server
  hosts: all
  gather_facts: false

  tasks:
  #------------------------------- LANZANDO EJECUCION DEL SCRIPT
    - name: Exec Script
      script: Nirvana/depuraLogsWLS.sh {{ depuration_theshold }} {{ domain_server_home | default([]) }} 

