- name: List linux packages installed.
  hosts: all
  gather_facts: true
  tasks:
    - name: Gather the rpm package facts
      package_facts:
        manager: auto

    - name: Print the rpm package facts
      debug:
        var: ansible_facts.packages
