---
- name: This playbook updates packages on any distro family
  hosts: all
  become: true
  tasks:
    - name: return motd to registered var
      command: sudo yum updateinfo
      register: updateinfo