---
- name: This playbook updates packages on any distro family
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: List available updates on Centos
      yum:
        list: updates
      register: redhat
      when: ansible_os_family == "RedHat"

    - name: List available updates on Ubuntu
      command: apt list --upgradable 
      register: ubuntu
      when: ansible_os_family == "Debian"

    - name: print the mother fucker variable redhat
      debug:
        var: redhat

    - set_fact: mensaje="{{redhat.stdout}}", para="enava@kionetworks.com"
    
    - import_tasks: plays/sendmail.yml