---
- name: This playbook updates packages on any distro family
  hosts: all
  become: true
  gather_facts: true
  vars:
    message:
      - redhat
      - suse
      - ubuntu

  tasks:
    - name: List available updates on Centos
      command: yum updateinfo
      register: redhat
      debug:
        var: redhat 
      when: ansible_distribution == "CentOS"

    - name: List available updates on Ubuntu
      command: apt list --upgradable
      register: ubuntu
      debug:
        var: ubuntu
      when: ansible_distribution == "Ubuntu"

    - name: List available updates on Suse
      command: zypper list-updates
      register: suse
      when: ansible_distribution == "Suse"

    - set_fact: mensaje= {{ message }}, para="enava@kionetworks.com"

    
    - import_tasks: plays/sendmail.yml
