---
- name: This playbook updates packages on any distro family
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: List available updates on Centos
      command: yum updateinfo
      register: redhat
      when: ansible_distribution == "CentOS"

    - name: List available updates on Ubuntu
      command: apt list --upgradable
      register: ubuntu
      when: ansible_distribution == "Ubuntu"

    - name: print the mother fucker variable ubuntu
      debug:
        var: ubuntu

    - name: print the mother fucker variable redhat
      debug:
        var: redhat

    - name: List available updates on Suse
      command: zypper list-updates
      register: suse
      when: ansible_distribution == "Suse"

    - set_fact: mensaje="redhat ubuntu", para="enava@kionetworks.com"

    
    - import_tasks: plays/sendmail.yml
