---
- name: This playbook updates packages on any distro family
  hosts: all
  gather_facts: true

  tasks:
    - name: List available updates on Ubuntu
      become: true
      command: apt list --upgradeable 
      register: ubuntu
      when: ansible_os_family == "Debian"

    - set_fact: mensaje="{{ubuntu.stdout}}", para="enava@kionetworks.com", asunto="Reporte de actualizaciones disponibles {{inventory_hostname}}"
      when: ansible_os_family == "Debian"
    
    - import_tasks: plays/sendmail.yml
      when: ansible_os_family == "Debian"