---
# This playbook lists the users in Windows hosts

- name: Run powershell script
  hosts: all 
  gather_facts: false
  tasks:
    - name: Run powershell script
      script: windowsFiles/ListUsers.ps1
