---
- name: This playbook updates packages on any distro family
  hosts: all
  tasks:
    - name: return motd to registered var
      become: true
      command: yum updateinfo
      register: updateinfo
      when: ansible_distribution == "CentOS"