---
- name: This playbook updates packages on any distro family
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: List available updates on Centos
      yum:
        list: updates
      when: ansible_os_family == "RedHat"

    - name: List available updates on Ubuntu
      apt: 
        list: updates
      when: ansible_os_family == "Debian"

    - name: print the mother fucker variable ubuntu
      debug:
        var: ubuntu

    - name: print the mother fucker variable redhat
      debug:
        var: redhat

    - name: List available updates on Suse
      command: zypper list-updates
      register: suse
      when: ansible_distribution == "Suse"

    - set_fact: mensaje="{{ubuntu}} {{redhat}}", para="enava@kionetworks.com"

    
    - import_tasks: plays/sendmail.yml
