---
- name: This playbook updates packages on any distro family
  hosts: all
  gather_facts: true

  tasks:
    - name: List available updates on Ubuntu
      become: true
      command: apt list --upgradable 
      register: ubuntu
      when: ansible_os_family == "Debian"

    - name: print the mother fucker variable redhat
      debug:
        var: Ubuntu

    - set_fact: mensaje="{{ubuntu}}", para="enava@kionetworks.com"
    
    - import_tasks: plays/sendmail.yml