---
- name: This playbook updates packages on any distro family
  hosts: all
  become: true
  tasks:
    - name: Upgrade all installed packages for Debian family
      apt:
        names: "*"
        state: latest
        update_cache: yes 
      when: ansible_os_family == 'Debian'
    - name: Upgrade all installed packages for OpenSUSE family
      zypper:
        name: "*"
        state: latest
      when: ansible_os_family == "Suse"
    - name: Upgrade all installed packages for RedHat family
      yum:
        name: "*" 
        state: latest
      when: ansible_os_family == "RedHat"
...
