---
- name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
  hosts: all
  vars:
    update_type: Updates
    para: <ebenitez@kionetworks.com>
    asunto: Ansible-report
    mensaje: vacio

  gather_facts: false

#------------------------------- GETTING NEW BOT'S PORT FROM HAPROXI CONFIG FILE

  tasks:
    - name: List Windows "{{ update_type }}"
      register: res
      win_updates:
        category_names: "{{ update_type }}"
        state: searched
        log_path: C:\ansible_wu.txt

    - set_fact: mensaje="{{ res }}"

    - import_tasks: plays/sendmail.yml
      vars:
        mensaje: "{{ mensaje }}"

# CriticalUpdates
# SecurityUpdates
# UpdateRollups
# Updates