---
- name: Envia Correo
  hosts: all
  vars:
    # To be defined by the user
    bot_name: Correo
    para: <ebenitez@kionetworks.com>
    asunto: Ansible-report
    msj: vacio

  gather_facts: false

#------------------------------- GETTING NEW BOT'S PORT FROM HAPROXI CONFIG FILE
  tasks:
    - name: Sending e-mail
      register: res
      command: "echo 'contenido del mail'"

    - set_fact: msj="{{ res }}"

    - import_tasks: plays/sendmail.yml
      vars:
        msj: "{{ msj }}"
