---
#------------------------------- INICIALIZANDO ARCHIVO DE RESULTADOS
- name: Inicialice file
  hosts: localhost
  vars:
    start: "["

  tasks:
    - name: Create Json File                                                                               
      copy:
        content: "{{ start }}"
        dest: "/tmp/report.json"
      delegate_to: 127.0.0.1

#------------------------------- GETTING UPDATES LIST
- name: Search Windows updates by category
  hosts: all
  vars:
    update_type: Updates
  gather_facts: false

  tasks:
    - name: List Windows "{{ update_type }}"
      register: res
      win_updates:
        category_names: "{{ update_type }}"
        state: searched
        log_path: C:\ansible_wu.txt

    - name: Write output to json
      lineinfile:
        line: " \"{{ inventory_hostname }}\": {{ res }} ,"
        insertafter: EOF
        dest: /tmp/report.json
      delegate_to: 127.0.0.1

#------------------------------- CERRANDO ARCHIVO DE RESULTADOS
- name: Close file
  hosts: localhost
  vars:
    end: "]"
    para: <ebenitez@kionetworks.com>
    asunto: Ansible-report
    mensaje: vacio

  tasks:
    - name: Close json file
      lineinfile:
        line: "{{ end }}"
        insertafter: EOF
        dest: /tmp/report.json
      delegate_to: 127.0.0.1

#------------------------------- TRANSOFRMANDO JSON TO XLSX

    - set_fact: inputfile="/tmp/report.json" outputfile="/tmp/report.xlsx"

    - import_tasks: plays/json2xlsx.yml

#------------------------------- ENVIANDO CORREO  

    - set_fact: mensaje="Contenido :D", adjuntos="/tmp/report.json, /tmp/report.xlsx"
    
    - import_tasks: plays/sendmail.yml

#------------------------------- LIMPIANDO ARCHIVOS TEMPORALES

    - local_action: file path=/tmp/report.json state=absent

    - local_action: file path=/tmp/report.xlsx state=absent

# CriticalUpdates
# SecurityUpdates
# UpdateRollups
# Updates