---
- name: Search-only, return list of found updates (if any), log to C:\ansible_wu.txt
  hosts: all
  vars:
    update_type: Updates
    para: <ebenitez@kionetworks.com>
    asunto: Ansible-report
    mensaje: vacio

  gather_facts: false

#------------------------------- GETTING NEW BOT'S PORT FROM HAPROXI CONFIG FILE
  tasks:
    - name: List Windows "{{ update_type }}"
      register: res
      win_updates:
        category_names: "{{ update_type }}"
        state: searched
        log_path: C:\ansible_wu.txt

    #- name: Write output to json
    #  local_action: copy content={{ res }} dest=/tmp/report.json

    - name: Write output to json
      lineinfile:
        line: "{{ res }}"
        insertafter: EOF
        dest: /tmp/report.json
      delegate_to: 127.0.0.1

#------------------------------- GETTING NEW BOT'S PORT FROM HAPROXI CONFIG FILE
- name: Sending email
  hosts: localhost
  vars:
    para: <ebenitez@kionetworks.com>
    asunto: Ansible-report
    mensaje: vacio
  tasks:

    - set_fact: mensaje="Contenido :D", adjuntos="/tmp/report.json"

    - import_tasks: plays/sendmail.yml

    - local_action: file path=/tmp/report.json state=absent

# CriticalUpdates
# SecurityUpdates
# UpdateRollups
# Updates