---
- name: Add a User
  hosts: all
  vars: windows_user: ansibletest
    ansible_user: lola
  gather_facts: false
  tasks:
    - name: Add User
      win_user:
        name: windows_user
        password: "4N$1bl32020"
        state: present
        groups:
         - Administrators
