---
- name: Add a User
  hosts: all
  vars: 
    windows_user: ansibletest
    windows_password: "4N$1bl32020"
    windows_group: "Administrators"
  gather_facts: false
  tasks:
    - name: Add User
      win_user:
        name: "{{ windows_user }}"
        password: "{{ windows_password }}"
        state: present
        groups:
         - "{{ windows_group }}"
