---
- name: Update a User's password
  hosts: all
  vars:
    windows_user: placeholder
    windows_password: placeholder
  gather_facts: false
  tasks:
    - name: Update Password
      win_user:
        name: "{{ windows_user }}"
        password: "{{ windows_password }}"
        update_password: always
