---
- name: Add a User
  hosts: all
  vars: 
    windows_user: ansibletest
    windows_password: "4N$1bl32020"
    windows_group: "Administrators"
  gather_facts: false
  tasks:
    - name: Add User
      win_user:
        name: "{{ windows_user }}"
        password: "{{ windows_password }}"
        state: present
        groups:
         - "{{ windows_group }}"
         
    - name: List available users
      win_shell: |
        $adsi = [ADSI]"WinNT://$env:COMPUTERNAME"
        $adsi.Children | where {$_.SchemaClassName -eq 'user'} | Foreach-Object {
        $groups = $_.Groups() | Foreach-Object {$_.GetType().InvokeMember("Name", 'GetProperty', $null, $_, $null)}
        $_ | Select-Object @{n='UserName';e={$_.Name}},@{n='Groups';e={$groups -join ';'}}
        }
      register: command
      args:
        stdout: always
        
    - name: Print Output
      debug: var=command.stdout_lines
