---
- name: Remove a User
  hosts: all
  vars:
    windows_user: placeholder
  gather_facts: false
  tasks:
    - name: Remove User
      win_user:
        name: "{{ windows_user }}"
        state: absent
