---
- name: Add a User
  hosts: all
  gather_facts: false
  tasks:
    - name: Add User
      win_user:
        name: ansible
        password: "4N$1bl32020"
        state: present
        groups:
         - Administrators
