---
- name: Update a User's password
  hosts: all
  gather_facts: false
  tasks:
    - name: Update Password
      win_user:
        name: ansible
        password: "4N$1bl32020UPDATED"
        update_password: always
